# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20170207_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
