# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20170208_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='map',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opposing_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_score',
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('BO1', 'Best of 1'), ('BO3', 'Best of 3'), ('BO5', 'Best of 5'), ('BO7', 'Best of 7')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
