# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20170208_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_score', models.IntegerField()),
                ('opposing_score', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Map')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='map',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opposing_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_score',
        ),
    ]
