# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_result_map_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(),
        ),
    ]
