# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_auto_20170208_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='opposing_score_first_half',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='opposing_score_second_half',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='team_score_first_half',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='team_score_second_half',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
