# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_auto_20170208_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Competition')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='cms.Team')),
                ('team1_roster', models.ManyToManyField(related_name='team1_roster', to='cms.Player')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='cms.Team')),
                ('team2_roster', models.ManyToManyField(related_name='team2_roster', to='cms.Player')),
            ],
        ),
    ]
