# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_auto_20170209_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_1st_score', models.IntegerField()),
                ('team1_2nd_score', models.IntegerField()),
                ('team1_ot_score', models.IntegerField()),
                ('team2_1st_score', models.IntegerField()),
                ('team2_2nd_score', models.IntegerField()),
                ('team2_ot_score', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Match')),
            ],
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='team',
        ),
        
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='cms.Player'),
        ),
        migrations.DeleteModel(
            name='TeamPlayer',
        ),
    ]
