# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_remove_player_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Result'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_roster',
            field=models.ManyToManyField(related_name='team1_roster', to='cms.TeamPlayer'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_roster',
            field=models.ManyToManyField(related_name='team2_roster', to='cms.TeamPlayer'),
        ),
    ]
