# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0042_result_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team1_roster',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2_roster',
        ),
    ]
