# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_auto_20170209_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Map')),
            ],
        ),
        migrations.CreateModel(
            name='MatchMapTeamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_half_score', models.IntegerField()),
                ('second_half_score', models.IntegerField()),
                ('overtime_score', models.IntegerField()),
                ('fielded_roster', models.ManyToManyField(to='cms.TeamPlayer')),
                ('match_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.MatchMap')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='teamresult',
            name='map',
        ),
        migrations.RemoveField(
            model_name='teamresult',
            name='match',
        ),
        migrations.RemoveField(
            model_name='teamresult',
            name='team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1_roster',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2_roster',
        ),
        migrations.DeleteModel(
            name='TeamResult',
        ),
        migrations.AddField(
            model_name='matchmap',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Match'),
        ),
    ]
