# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0049_auto_20170212_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='datetime_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
