# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestentry',
            name='full_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
