# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20170213_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestentry',
            name='social_provider',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
