# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_contestentry_social_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestentry',
            name='social_provider',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
