# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20170213_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
