# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 14:58
from __future__ import unicode_literals

import contests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20170213_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='graphic',
            field=models.ImageField(blank=True, null=True, upload_to=contests.models.graphic_file_path),
        ),
    ]
