# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:03
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_contest_graphic'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='description',
            field=redactor.fields.RedactorField(default=1),
            preserve_default=False,
        ),
    ]
