# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_contest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(),
        ),
    ]
